(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const a={navBurgerMenu:document.querySelector(".js-burgerMenu-container"),navList:document.querySelector(".js-navList"),navItemMenu:document.querySelector(".js-nav-item")};function u(){const e=document.createElement("div");return e.classList.add("headerModal","modal-navList"),e.innerHTML=`
      <ul class='header-modal-list'>
        <li><a href="#home">Home</a></li>
        <li><a href="#about-us">About Us</a></li>
        <li><a href="#benefits">Benefits</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="#faq">FAQ</a></li>
      </ul>
  `,e}function r(e){const s=a.navBurgerMenu.querySelector("use");e?s.setAttribute("xlink:href","../img/svg/sprite.svg#icon-close-cross"):s.setAttribute("xlink:href","../img/svg/sprite.svg#icon-burger-menu")}function d(){let e=document.querySelector(".headerModal");const s=window.innerWidth>=1200;e||(e=u(),a.navList.insertAdjacentElement("afterend",e));const n=e.classList.contains("show");s?n&&(e.classList.remove("show"),r(!1)):(e.classList.toggle("show"),r(!n))}function f(){console.log("first");const e=document.querySelector(".headerModal");window.innerWidth>=1200&&e&&e.classList.contains("show")&&(e.classList.remove("show"),r(!1))}a.navBurgerMenu.addEventListener("click",d);window.addEventListener("resize",f);const l={faqButton:document.getElementsByClassName("faq-collapse"),faqText:document.getElementsByClassName("faq-text")};console.log(l.faqButton);for(let e=0;e<l.faqButton.length;e++)l.faqButton[e].addEventListener("click",function(){this.classList.toggle("active");const s=this.nextElementSibling;this.classList.contains("active")?s.style.display="block":s.style.display="none"});
//# sourceMappingURL=commonHelpers.js.map
