(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const c={navBurgerMenu:document.querySelector(".js-burgerMenu-container"),navList:document.querySelector(".js-navList"),navItemMenu:document.querySelector(".js-nav-item")};function a(){const e=document.createElement("div");return e.classList.add("headerModal","modal-navList"),e.innerHTML=`
      <ul class='header-modal-list'>
        <li><a href="#home">Home</a></li>
        <li><a href="#about-us">About Us</a></li>
        <li><a href="#benefits">Benefits</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="#faq">FAQ</a></li>
      </ul>
  `,e}function l(e){const n=c.navBurgerMenu.querySelector("use");e?n.setAttribute("xlink:href","../img/svg/sprite.svg#icon-close-cross"):n.setAttribute("xlink:href","../img/svg/sprite.svg#icon-burger-menu")}function u(){let e=document.querySelector(".headerModal");const n=window.innerWidth>=1200;e||(e=a(),c.navList.insertAdjacentElement("afterend",e));const r=e.classList.contains("show");n?r&&(e.classList.remove("show"),l(!1)):(e.classList.toggle("show"),l(!r))}function d(){const e=document.querySelector(".headerModal");window.innerWidth>=1200&&e&&e.classList.contains("show")&&(e.classList.remove("show"),l(!1))}c.navBurgerMenu.addEventListener("click",u);window.addEventListener("resize",d);$(".gallery-container").slick({infinite:!0,initialSlide:0,autoplaySpeed:1e3,focusOnSelect:!0,centerMode:!0,centerPadding:"20px",slidesToShow:3,responsive:[{breakpoint:768,settings:{slidesToShow:1,centerPadding:"20px"}},{breakpoint:1200,settings:{slidesToShow:3,centerPadding:"20px"}}],prevArrow:'<button class="slick-prev"></button>',nextArrow:'<button class="slick-next"></button>'});$(".gallery-container").on("beforeChange",function(e,n,r,o){console.log(o)});
//# sourceMappingURL=commonHelpers.js.map
