(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const c={navBurgerMenu:document.querySelector(".js-burgerMenu-container"),navList:document.querySelector(".js-navList"),navItemMenu:document.querySelector(".js-nav-item")};function u(){const e=document.createElement("div");return e.classList.add("headerModal","modal-navList"),e.innerHTML=`
      <ul class='header-modal-list'>
        <li><a href="#home">Home</a></li>
        <li><a href="#about-us">About Us</a></li>
        <li><a href="#benefits">Benefits</a></li>
        <li><a href="#gallery">Gallery</a></li>
        <li><a href="#faq">FAQ</a></li>
      </ul>
  `,e}function r(e){const s=c.navBurgerMenu.querySelector("use");e?s.setAttribute("xlink:href","../img/svg/sprite.svg#icon-close-cross"):s.setAttribute("xlink:href","../img/svg/sprite.svg#icon-burger-menu")}function d(){let e=document.querySelector(".headerModal");const s=window.innerWidth>=1200;e||(e=u(),c.navList.insertAdjacentElement("afterend",e));const o=e.classList.contains("show");s?o&&(e.classList.remove("show"),r(!1)):(e.classList.toggle("show"),r(!o))}function f(){const e=document.querySelector(".headerModal");window.innerWidth>=1200&&e&&e.classList.contains("show")&&(e.classList.remove("show"),r(!1))}c.navBurgerMenu.addEventListener("click",d);window.addEventListener("resize",f);const l={faqButton:document.getElementsByClassName("faq-collapse"),faqText:document.getElementsByClassName("faq-text")};console.log(l.faqButton);for(let e=0;e<l.faqButton.length;e++)l.faqButton[e].addEventListener("click",function(){this.classList.toggle("active");const s=this.nextElementSibling;this.classList.contains("active")?s.style.display="block":s.style.display="none"});$(".gallery-container").slick({infinite:!0,initialSlide:0,focusOnSelect:!0,centerMode:!0,centerPadding:"20px",slidesToShow:3,responsive:[{breakpoint:768,settings:{slidesToShow:1,centerPadding:"20px"}},{breakpoint:1200,settings:{slidesToShow:3,centerPadding:"20px"}}],prevArrow:'<button class="slick-prev"></button>',nextArrow:'<button class="slick-next"></button>'});
//# sourceMappingURL=commonHelpers.js.map
